### PR TITLE
Fix typo in cython.yml

### PR DESCRIPTION
**Pull request by da-woods**
I think this is stopping the majority of the tests from running.

See https://github.com/cython/cython/pull/4471#issuecomment-980230790

### CODE REVIEW

**Comment by mattip** [comment]
Thanks, this is part of the misnamed PR #5

**Comment by da-woods** [comment]
> Thanks, this is part of the misnamed PR #5

Great - I'll close this and the other one then.

**Comment by mattip** [comment]
I merged theses changes in #5. The [latest run](https://github.com/pypy/binary-testing/actions/runs/1513145900) ran 949 tests on linux, 914 on mac, 836 on windows. The next step will be to try to make them all pass.

**Comment by da-woods** [comment]
It looks like the main issue is an unexpected "did you mean ..." in an exception message, which is easily ignored, and most of the rest is passing (I only looked at the Ubuntu tests though, so maybe Windows/Mac is worse...)

**Pull request closed without merging**
